--------------------------------------------------------
--  File created - Thursday-March-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CREDIT_NOTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROPERTYPRO"."CREDIT_NOTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INVOICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROPERTYPRO"."INVOICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LEASE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROPERTYPRO"."LEASE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RECEIPT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROPERTYPRO"."RECEIPT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence WO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROPERTYPRO"."WO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ASSETS
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."ASSETS" 
   (	"ASSET_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSET_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ASSET_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PROPERTY_ID" NUMBER, 
	"ASSET_CATEGORY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ASSET_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MANUFACTURER" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SERIAL_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PURCHASE_DATE" DATE, 
	"PURCHASE_COST" NUMBER(15,2), 
	"WARRANTY_EXPIRY_DATE" DATE, 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVE', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "PROPERTYPRO"."ASSETS"  IS 'Property assets and equipment';
--------------------------------------------------------
--  DDL for Table COMPLIANCE_RECORDS
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" 
   (	"COMPLIANCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"COMPLIANCE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PROPERTY_ID" NUMBER, 
	"COMPLIANCE_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"COMPLIANCE_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"COMPLIANCE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ISSUING_AUTHORITY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ISSUE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"DUE_DATE" DATE, 
	"COMPLETION_DATE" DATE, 
	"NEXT_DUE_DATE" DATE, 
	"FREQUENCY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"RISK_LEVEL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"COST" NUMBER(15,2), 
	"CERTIFICATE_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DOCUMENT_PATH" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTES" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("NOTES") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS"  IS 'Compliance tracking with 52 Kenya-specific types';
--------------------------------------------------------
--  DDL for Table CREDIT_NOTES
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."CREDIT_NOTES" 
   (	"CREDIT_NOTE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CREDIT_NOTE_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_ID" NUMBER, 
	"TENANT_ID" NUMBER, 
	"CREDIT_DATE" DATE DEFAULT SYSDATE, 
	"AMOUNT" NUMBER(15,2), 
	"REASON" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"ERP_CREDIT_NOTE_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SYNC_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"APPROVED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVED_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "PROPERTYPRO"."CREDIT_NOTES"  IS 'Credit notes for refunds and adjustments';
--------------------------------------------------------
--  DDL for Table LEASES
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."LEASES" 
   (	"LEASE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LEASE_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PROPERTY_ID" NUMBER, 
	"TENANT_ID" NUMBER, 
	"SPACE_ID" NUMBER, 
	"UNIT_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LEASE_START_DATE" DATE, 
	"LEASE_END_DATE" DATE, 
	"RENT_COMMENCEMENT_DATE" DATE, 
	"FREE_RENT_PERIOD_MONTHS" NUMBER(3,0), 
	"TERM_MONTHS" NUMBER(4,0), 
	"BASE_RENT" NUMBER(15,2), 
	"CAM_CHARGES" NUMBER(15,2) DEFAULT 0, 
	"SERVICE_CHARGE" NUMBER(15,2) DEFAULT 0, 
	"PARKING_FEE" NUMBER(15,2) DEFAULT 0, 
	"RENT_AMOUNT" NUMBER(15,2), 
	"SECURITY_DEPOSIT" NUMBER(15,2), 
	"SECURITY_DEPOSIT_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ADVANCE_RENT_MONTHS" NUMBER(2,0), 
	"PAYMENT_FREQUENCY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_DAY" NUMBER(2,0), 
	"LEASE_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LEASE_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVE', 
	"PARKING_SPACES_ALLOCATED" NUMBER(3,0), 
	"ESCALATION_RATE" NUMBER(5,2), 
	"ESCALATION_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ESCALATION_FREQUENCY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NEXT_ESCALATION_DATE" DATE, 
	"RENEWAL_OPTION" NUMBER(1,0) DEFAULT 0, 
	"RENEWAL_NOTICE_DAYS" NUMBER(3,0), 
	"NOTICE_PERIOD_DAYS" NUMBER(3,0), 
	"SUBLEASE_ALLOWED" NUMBER(1,0) DEFAULT 0, 
	"ASSIGNMENT_ALLOWED" NUMBER(1,0) DEFAULT 0, 
	"UTILITY_CHARGES_INCLUDED" NUMBER(1,0) DEFAULT 0, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "PROPERTYPRO"."LEASES"  IS 'Enhanced lease agreements with CAM charges, parking, and escalation tracking';
--------------------------------------------------------
--  DDL for Table LEASE_REQUESTS
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."LEASE_REQUESTS" 
   (	"LEASE_REQUEST_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"REQUEST_NUMBER" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"REQUESTED_BY_USER_ID" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"REQUESTED_BY_USERNAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"REQUESTED_BY_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"PROPERTY_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"FLOOR_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"SPACE_IDS" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"SELECTION_TYPE" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'UNITS', 
	"REQUESTED_AREA_SQM" NUMBER(12,2), 
	"UNIT_TYPE_PREFERENCE" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTES" CLOB COLLATE "USING_NLS_COMP", 
	"REQUEST_TYPE" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'LEASE', 
	"LEASE_TYPE" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"PREFERRED_START_DATE" DATE, 
	"PREFERRED_END_DATE" DATE, 
	"TERM_MONTHS" NUMBER(5,0), 
	"BUDGET_OR_RENT_NOTES" CLOB COLLATE "USING_NLS_COMP", 
	"CONTACT_PHONE" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"ROOM_REQUEST_TYPE" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ROOM_DATE_FROM" DATE, 
	"ROOM_DATE_TO" DATE, 
	"DURATION_HOURS" NUMBER(6,2), 
	"CAPACITY" NUMBER(5,0), 
	"AMENITIES_REQUIRED" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ROOM_NOTES" CLOB COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"APPROVED_BY" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVED_DATE" TIMESTAMP (6), 
	"REJECTION_REASON" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LAST_UPDATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("NOTES") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("BUDGET_OR_RENT_NOTES") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ROOM_NOTES") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("REJECTION_REASON") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "PROPERTYPRO"."LEASE_REQUESTS"."REQUEST_TYPE" IS 'LEASE, RENT, or ROOMS';
   COMMENT ON COLUMN "PROPERTYPRO"."LEASE_REQUESTS"."ROOM_REQUEST_TYPE" IS 'MEETING_ROOM, CONFERENCE, etc. when request_type=ROOMS';
   COMMENT ON TABLE "PROPERTYPRO"."LEASE_REQUESTS"  IS 'Customer lease/rent/room requests; request_type: LEASE, RENT, or ROOMS';
--------------------------------------------------------
--  DDL for Table PAYMENT_RECEIPTS
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" 
   (	"RECEIPT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RECEIPT_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_ID" NUMBER, 
	"TENANT_ID" NUMBER, 
	"PAYMENT_DATE" DATE DEFAULT SYSDATE, 
	"AMOUNT_PAID" NUMBER(15,2), 
	"PAYMENT_METHOD" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_REFERENCE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BANK_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESSED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESSING_DATE" DATE DEFAULT SYSDATE, 
	"ERP_RECEIPT_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SYNC_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SYNC_DATE" DATE, 
	"NOTES" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS"  IS 'Payment receipts with M-Pesa and bank transfer support';
--------------------------------------------------------
--  DDL for Table PROPERTIES
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."PROPERTIES" 
   (	"PROPERTY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PROPERTY_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PROPERTY_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PROPERTY_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVE', 
	"ADDRESS_LINE1" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_LINE2" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTAL_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL_AREA" NUMBER(12,2), 
	"TOTAL_UNITS" NUMBER, 
	"YEAR_BUILT" NUMBER(4,0), 
	"OWNERSHIP_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ACQUISITION_DATE" DATE, 
	"ACQUISITION_COST" NUMBER(15,2), 
	"CURRENT_VALUE" NUMBER(15,2), 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE, 
	"TOTAL_FLOORS" NUMBER(5,0), 
	"LATITUDE" NUMBER(10,7), 
	"LONGITUDE" NUMBER(10,7)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "PROPERTYPRO"."PROPERTIES"."TOTAL_FLOORS" IS 'Total number of floors in the building';
   COMMENT ON COLUMN "PROPERTYPRO"."PROPERTIES"."LATITUDE" IS 'Latitude coordinate (e.g. -1.2921)';
   COMMENT ON COLUMN "PROPERTYPRO"."PROPERTIES"."LONGITUDE" IS 'Longitude coordinate (e.g. 36.8219)';
   COMMENT ON TABLE "PROPERTYPRO"."PROPERTIES"  IS 'Master table for all properties in the portfolio';
--------------------------------------------------------
--  DDL for Table RENT_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."RENT_SCHEDULE" 
   (	"SCHEDULE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LEASE_ID" NUMBER, 
	"DUE_DATE" DATE, 
	"AMOUNT" NUMBER(15,2), 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"PAYMENT_DATE" DATE, 
	"PAYMENT_REFERENCE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table SPACES
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."SPACES" 
   (	"SPACE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SPACE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PROPERTY_ID" NUMBER, 
	"SPACE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SPACE_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FLOOR_NUMBER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"UNIT_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AREA" NUMBER(12,2), 
	"AREA_UNIT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'SQM', 
	"OCCUPANCY_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'VACANT', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE, 
	"CATEGORY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'SPACE', 
	"FLOOR_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "PROPERTYPRO"."SPACES"."CATEGORY" IS 'SPACE or UNIT';
   COMMENT ON COLUMN "PROPERTYPRO"."SPACES"."FLOOR_ID" IS 'Optional FK to floors.floor_id; can also use property_id + floor_number';
   COMMENT ON TABLE "PROPERTYPRO"."SPACES"  IS 'Individual spaces/units within properties';
--------------------------------------------------------
--  DDL for Table TENANTS
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."TENANTS" 
   (	"TENANT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENANT_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TENANT_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"TENANT_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_PERSON" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_PHONE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS_REGISTRATION_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVE', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "PROPERTYPRO"."TENANTS"  IS 'Master table for all tenants';
--------------------------------------------------------
--  DDL for Table TENANT_INVOICES
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."TENANT_INVOICES" 
   (	"INVOICE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"INVOICE_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TENANT_ID" NUMBER, 
	"LEASE_ID" NUMBER, 
	"PROPERTY_ID" NUMBER, 
	"INVOICE_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_DATE" DATE DEFAULT SYSDATE, 
	"DUE_DATE" DATE, 
	"BILLING_PERIOD_START" DATE, 
	"BILLING_PERIOD_END" DATE, 
	"AMOUNT" NUMBER(15,2), 
	"VAT_RATE" NUMBER(5,2) DEFAULT 16.00, 
	"VAT_AMOUNT" NUMBER(15,2) DEFAULT 0, 
	"WITHHOLDING_TAX_RATE" NUMBER(5,2) DEFAULT 10.00, 
	"WITHHOLDING_TAX_AMOUNT" NUMBER(15,2) DEFAULT 0, 
	"TOTAL_AMOUNT" NUMBER(15,2), 
	"NET_AMOUNT_DUE" NUMBER(15,2), 
	"AMOUNT_PAID" NUMBER(15,2) DEFAULT 0, 
	"BALANCE" NUMBER(15,2), 
	"PAYMENT_METHOD" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_REFERENCE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"PAYMENT_DATE" DATE, 
	"DAYS_OVERDUE" NUMBER(5,0), 
	"COLLECTION_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"GL_ACCOUNT_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_INVOICE_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SYNC_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SYNC_DATE" DATE, 
	"ERP_ERROR_MESSAGE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTES" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("NOTES") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON TABLE "PROPERTYPRO"."TENANT_INVOICES"  IS 'Tenant invoices with Kenya tax calculations (VAT, WHT)';
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."USERS" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD_HASH" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"FULL_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'USER', 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVE', 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_LOGIN_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "PROPERTYPRO"."USERS"  IS 'Application users for login and API authentication';
--------------------------------------------------------
--  DDL for Table VENDORS
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."VENDORS" 
   (	"VENDOR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"VENDOR_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"VENDOR_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"VENDOR_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_PERSON" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_PHONE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS_REGISTRATION_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVE', 
	"RATING" NUMBER(2,1), 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "PROPERTYPRO"."VENDORS"  IS 'Vendor and contractor information';
--------------------------------------------------------
--  DDL for Table WORK_ORDERS
--------------------------------------------------------

  CREATE TABLE "PROPERTYPRO"."WORK_ORDERS" 
   (	"WORK_ORDER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"WORK_ORDER_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PROPERTY_ID" NUMBER, 
	"ASSET_ID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" CLOB COLLATE "USING_NLS_COMP", 
	"WORK_ORDER_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIORITY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ASSIGNED_TO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"VENDOR_ID" NUMBER, 
	"REPORTED_DATE" DATE DEFAULT SYSDATE, 
	"SCHEDULED_DATE" DATE, 
	"COMPLETED_DATE" DATE, 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OPEN', 
	"ESTIMATED_COST" NUMBER(15,2), 
	"ACTUAL_COST" NUMBER(15,2), 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON TABLE "PROPERTYPRO"."WORK_ORDERS"  IS 'Maintenance and work order requests';
REM INSERTING into PROPERTYPRO.ASSETS
SET DEFINE OFF;
Insert into PROPERTYPRO.ASSETS (ASSET_ID,ASSET_CODE,ASSET_NAME,PROPERTY_ID,ASSET_CATEGORY,ASSET_TYPE,MANUFACTURER,MODEL_NUMBER,SERIAL_NUMBER,PURCHASE_DATE,PURCHASE_COST,WARRANTY_EXPIRY_DATE,STATUS,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (2,'AST-1771780061521','Central HVAC Unit - Westlands',21,'HVAC','Chiller','Carrier','30XA-1000','CHW-2024-001',to_date('22-FEB-26','DD-MON-RR'),850000,to_date('13-MAR-26','DD-MON-RR'),'ACTIVE',null,to_date('22-FEB-26','DD-MON-RR'),null,to_date('22-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.ASSETS (ASSET_ID,ASSET_CODE,ASSET_NAME,PROPERTY_ID,ASSET_CATEGORY,ASSET_TYPE,MANUFACTURER,MODEL_NUMBER,SERIAL_NUMBER,PURCHASE_DATE,PURCHASE_COST,WARRANTY_EXPIRY_DATE,STATUS,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (21,'AST-1772528660375','Central HVAC Unit - Eastlands',61,'HVAC','Pump',null,null,null,null,null,null,'ACTIVE',null,to_date('03-MAR-26','DD-MON-RR'),null,to_date('03-MAR-26','DD-MON-RR'));
REM INSERTING into PROPERTYPRO.COMPLIANCE_RECORDS
SET DEFINE OFF;
REM INSERTING into PROPERTYPRO.CREDIT_NOTES
SET DEFINE OFF;
REM INSERTING into PROPERTYPRO.LEASES
SET DEFINE OFF;
Insert into PROPERTYPRO.LEASES (LEASE_ID,LEASE_NUMBER,PROPERTY_ID,TENANT_ID,SPACE_ID,UNIT_NUMBER,LEASE_START_DATE,LEASE_END_DATE,RENT_COMMENCEMENT_DATE,FREE_RENT_PERIOD_MONTHS,TERM_MONTHS,BASE_RENT,CAM_CHARGES,SERVICE_CHARGE,PARKING_FEE,RENT_AMOUNT,SECURITY_DEPOSIT,SECURITY_DEPOSIT_TYPE,ADVANCE_RENT_MONTHS,PAYMENT_FREQUENCY,PAYMENT_DAY,LEASE_TYPE,LEASE_CATEGORY,STATUS,PARKING_SPACES_ALLOCATED,ESCALATION_RATE,ESCALATION_TYPE,ESCALATION_FREQUENCY,NEXT_ESCALATION_DATE,RENEWAL_OPTION,RENEWAL_NOTICE_DAYS,NOTICE_PERIOD_DAYS,SUBLEASE_ALLOWED,ASSIGNMENT_ALLOWED,UTILITY_CHARGES_INCLUDED,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (24,'LEASE-1771778922618',21,3,null,null,to_date('22-FEB-26','DD-MON-RR'),to_date('22-FEB-26','DD-MON-RR'),null,null,0,2500,0,0,0,2500,250000,null,null,'QUARTERLY',null,'COMMERCIAL',null,'ACTIVE',null,null,null,null,null,0,null,null,0,0,0,null,to_date('22-FEB-26','DD-MON-RR'),null,to_date('22-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.LEASES (LEASE_ID,LEASE_NUMBER,PROPERTY_ID,TENANT_ID,SPACE_ID,UNIT_NUMBER,LEASE_START_DATE,LEASE_END_DATE,RENT_COMMENCEMENT_DATE,FREE_RENT_PERIOD_MONTHS,TERM_MONTHS,BASE_RENT,CAM_CHARGES,SERVICE_CHARGE,PARKING_FEE,RENT_AMOUNT,SECURITY_DEPOSIT,SECURITY_DEPOSIT_TYPE,ADVANCE_RENT_MONTHS,PAYMENT_FREQUENCY,PAYMENT_DAY,LEASE_TYPE,LEASE_CATEGORY,STATUS,PARKING_SPACES_ALLOCATED,ESCALATION_RATE,ESCALATION_TYPE,ESCALATION_FREQUENCY,NEXT_ESCALATION_DATE,RENEWAL_OPTION,RENEWAL_NOTICE_DAYS,NOTICE_PERIOD_DAYS,SUBLEASE_ALLOWED,ASSIGNMENT_ALLOWED,UTILITY_CHARGES_INCLUDED,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (1,'LSE-20240101-1000',1,1,null,'UNIT-101',to_date('01-JAN-24','DD-MON-RR'),to_date('31-DEC-26','DD-MON-RR'),null,null,null,15000,0,0,0,15000,45000,null,null,'MONTHLY',null,'COMMERCIAL','GROSS','ACTIVE',null,3.5,'FIXED','ANNUAL',null,0,null,null,0,0,0,null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.LEASES (LEASE_ID,LEASE_NUMBER,PROPERTY_ID,TENANT_ID,SPACE_ID,UNIT_NUMBER,LEASE_START_DATE,LEASE_END_DATE,RENT_COMMENCEMENT_DATE,FREE_RENT_PERIOD_MONTHS,TERM_MONTHS,BASE_RENT,CAM_CHARGES,SERVICE_CHARGE,PARKING_FEE,RENT_AMOUNT,SECURITY_DEPOSIT,SECURITY_DEPOSIT_TYPE,ADVANCE_RENT_MONTHS,PAYMENT_FREQUENCY,PAYMENT_DAY,LEASE_TYPE,LEASE_CATEGORY,STATUS,PARKING_SPACES_ALLOCATED,ESCALATION_RATE,ESCALATION_TYPE,ESCALATION_FREQUENCY,NEXT_ESCALATION_DATE,RENEWAL_OPTION,RENEWAL_NOTICE_DAYS,NOTICE_PERIOD_DAYS,SUBLEASE_ALLOWED,ASSIGNMENT_ALLOWED,UTILITY_CHARGES_INCLUDED,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (2,'LSE-20240115-1001',2,2,null,'UNIT-201',to_date('15-JAN-24','DD-MON-RR'),to_date('14-JAN-27','DD-MON-RR'),null,null,null,25000,0,0,0,25000,75000,null,null,'MONTHLY',null,'OFFICE','GROSS','ACTIVE',null,4,'FIXED','ANNUAL',null,0,null,null,0,0,0,null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.LEASES (LEASE_ID,LEASE_NUMBER,PROPERTY_ID,TENANT_ID,SPACE_ID,UNIT_NUMBER,LEASE_START_DATE,LEASE_END_DATE,RENT_COMMENCEMENT_DATE,FREE_RENT_PERIOD_MONTHS,TERM_MONTHS,BASE_RENT,CAM_CHARGES,SERVICE_CHARGE,PARKING_FEE,RENT_AMOUNT,SECURITY_DEPOSIT,SECURITY_DEPOSIT_TYPE,ADVANCE_RENT_MONTHS,PAYMENT_FREQUENCY,PAYMENT_DAY,LEASE_TYPE,LEASE_CATEGORY,STATUS,PARKING_SPACES_ALLOCATED,ESCALATION_RATE,ESCALATION_TYPE,ESCALATION_FREQUENCY,NEXT_ESCALATION_DATE,RENEWAL_OPTION,RENEWAL_NOTICE_DAYS,NOTICE_PERIOD_DAYS,SUBLEASE_ALLOWED,ASSIGNMENT_ALLOWED,UTILITY_CHARGES_INCLUDED,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (3,'LSE-20240201-1002',3,3,null,'UNIT-A1',to_date('01-FEB-24','DD-MON-RR'),to_date('31-JAN-29','DD-MON-RR'),null,null,null,50000,0,0,0,50000,150000,null,null,'MONTHLY',null,'INDUSTRIAL','TRIPLE_NET','ACTIVE',null,3,'FIXED','ANNUAL',null,0,null,null,0,0,0,null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'));
REM INSERTING into PROPERTYPRO.LEASE_REQUESTS
SET DEFINE OFF;
REM INSERTING into PROPERTYPRO.PAYMENT_RECEIPTS
SET DEFINE OFF;
REM INSERTING into PROPERTYPRO.PROPERTIES
SET DEFINE OFF;
Insert into PROPERTYPRO.PROPERTIES (PROPERTY_ID,PROPERTY_CODE,PROPERTY_NAME,PROPERTY_TYPE,STATUS,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,COUNTRY,POSTAL_CODE,TOTAL_AREA,TOTAL_UNITS,YEAR_BUILT,OWNERSHIP_TYPE,ACQUISITION_DATE,ACQUISITION_COST,CURRENT_VALUE,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE,TOTAL_FLOORS,LATITUDE,LONGITUDE) values (21,'PROP-1771777770798','Westlands Tower','COMMERCIAL','ACTIVE','100 Westlands Road',null,'Nairobi','Nairobi','Kenya','00100',45000,26,2019,null,null,null,null,null,to_date('22-FEB-26','DD-MON-RR'),null,to_date('22-FEB-26','DD-MON-RR'),null,null,null);
Insert into PROPERTYPRO.PROPERTIES (PROPERTY_ID,PROPERTY_CODE,PROPERTY_NAME,PROPERTY_TYPE,STATUS,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,COUNTRY,POSTAL_CODE,TOTAL_AREA,TOTAL_UNITS,YEAR_BUILT,OWNERSHIP_TYPE,ACQUISITION_DATE,ACQUISITION_COST,CURRENT_VALUE,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE,TOTAL_FLOORS,LATITUDE,LONGITUDE) values (84,'PROP-1773608760878','Tower-B','COMMERCIAL','ACTIVE','Tower-B',null,'Chennai','Tamil Nadu','India','600044',429,23,null,null,null,null,null,null,to_date('15-MAR-26','DD-MON-RR'),null,to_date('16-MAR-26','DD-MON-RR'),4,null,null);
Insert into PROPERTYPRO.PROPERTIES (PROPERTY_ID,PROPERTY_CODE,PROPERTY_NAME,PROPERTY_TYPE,STATUS,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,COUNTRY,POSTAL_CODE,TOTAL_AREA,TOTAL_UNITS,YEAR_BUILT,OWNERSHIP_TYPE,ACQUISITION_DATE,ACQUISITION_COST,CURRENT_VALUE,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE,TOTAL_FLOORS,LATITUDE,LONGITUDE) values (1,'PROP-001','Downtown Plaza','COMMERCIAL','ACTIVE','123 Main Street',null,'New York','NY','USA','10001',50000,25,2015,'OWNED',to_date('15-JUN-15','DD-MON-RR'),15000000,18000000,null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'),null,null,null);
Insert into PROPERTYPRO.PROPERTIES (PROPERTY_ID,PROPERTY_CODE,PROPERTY_NAME,PROPERTY_TYPE,STATUS,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,COUNTRY,POSTAL_CODE,TOTAL_AREA,TOTAL_UNITS,YEAR_BUILT,OWNERSHIP_TYPE,ACQUISITION_DATE,ACQUISITION_COST,CURRENT_VALUE,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE,TOTAL_FLOORS,LATITUDE,LONGITUDE) values (2,'PROP-002','Riverside Tower','COMMERCIAL','ACTIVE','456 River Road',null,'Chicago','IL','USA','60601',75000,40,2018,'OWNED',to_date('20-MAR-18','DD-MON-RR'),25000000,30000000,null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'),null,null,null);
Insert into PROPERTYPRO.PROPERTIES (PROPERTY_ID,PROPERTY_CODE,PROPERTY_NAME,PROPERTY_TYPE,STATUS,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,COUNTRY,POSTAL_CODE,TOTAL_AREA,TOTAL_UNITS,YEAR_BUILT,OWNERSHIP_TYPE,ACQUISITION_DATE,ACQUISITION_COST,CURRENT_VALUE,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE,TOTAL_FLOORS,LATITUDE,LONGITUDE) values (3,'PROP-003','Tech Park Building A','INDUSTRIAL','ACTIVE','789 Innovation Drive',null,'San Francisco','CA','USA','94102',100000,15,2020,'LEASED',to_date('10-JAN-20','DD-MON-RR'),35000000,40000000,null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'),null,null,null);
Insert into PROPERTYPRO.PROPERTIES (PROPERTY_ID,PROPERTY_CODE,PROPERTY_NAME,PROPERTY_TYPE,STATUS,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,COUNTRY,POSTAL_CODE,TOTAL_AREA,TOTAL_UNITS,YEAR_BUILT,OWNERSHIP_TYPE,ACQUISITION_DATE,ACQUISITION_COST,CURRENT_VALUE,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE,TOTAL_FLOORS,LATITUDE,LONGITUDE) values (41,'PROP-1771875114175','Suncity','COMMERCIAL','ACTIVE','121 Suncity st',null,'Nairobi','Alabama','USA','00100',12322,5,2019,null,null,null,null,null,to_date('23-FEB-26','DD-MON-RR'),null,to_date('23-FEB-26','DD-MON-RR'),null,null,null);
Insert into PROPERTYPRO.PROPERTIES (PROPERTY_ID,PROPERTY_CODE,PROPERTY_NAME,PROPERTY_TYPE,STATUS,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,COUNTRY,POSTAL_CODE,TOTAL_AREA,TOTAL_UNITS,YEAR_BUILT,OWNERSHIP_TYPE,ACQUISITION_DATE,ACQUISITION_COST,CURRENT_VALUE,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE,TOTAL_FLOORS,LATITUDE,LONGITUDE) values (61,'PROP-1772452457491','Lake City','COMMERCIAL','ACTIVE','121 lake st',null,'Nairobi','Alabama','USA','00100',null,null,null,null,null,null,null,null,to_date('02-MAR-26','DD-MON-RR'),null,to_date('02-MAR-26','DD-MON-RR'),null,null,null);
REM INSERTING into PROPERTYPRO.RENT_SCHEDULE
SET DEFINE OFF;
REM INSERTING into PROPERTYPRO.SPACES
SET DEFINE OFF;
REM INSERTING into PROPERTYPRO.TENANTS
SET DEFINE OFF;
Insert into PROPERTYPRO.TENANTS (TENANT_ID,TENANT_CODE,TENANT_NAME,TENANT_TYPE,CONTACT_PERSON,CONTACT_EMAIL,CONTACT_PHONE,BUSINESS_REGISTRATION_NUMBER,TAX_ID,STATUS,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (21,'TEN-MLXT9SBZ','Raman','CORPORATE','Praveen Sakthivel','praveenshakthiv@gmail.com','09600746110',null,null,'ACTIVE',null,to_date('22-FEB-26','DD-MON-RR'),null,to_date('22-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.TENANTS (TENANT_ID,TENANT_CODE,TENANT_NAME,TENANT_TYPE,CONTACT_PERSON,CONTACT_EMAIL,CONTACT_PHONE,BUSINESS_REGISTRATION_NUMBER,TAX_ID,STATUS,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (1,'TEN-001','Acme Corporation','CORPORATE','John Smith','john.smith@acme.com','+1-555-0101','BRN-123456','TAX-789012','ACTIVE',null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.TENANTS (TENANT_ID,TENANT_CODE,TENANT_NAME,TENANT_TYPE,CONTACT_PERSON,CONTACT_EMAIL,CONTACT_PHONE,BUSINESS_REGISTRATION_NUMBER,TAX_ID,STATUS,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (2,'TEN-002','Tech Solutions Inc','CORPORATE','Jane Doe','jane.doe@techsolutions.com','+1-555-0102','BRN-234567','TAX-890123','ACTIVE',null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.TENANTS (TENANT_ID,TENANT_CODE,TENANT_NAME,TENANT_TYPE,CONTACT_PERSON,CONTACT_EMAIL,CONTACT_PHONE,BUSINESS_REGISTRATION_NUMBER,TAX_ID,STATUS,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (3,'TEN-003','Global Enterprises','CORPORATE','Bob Johnson','bob.johnson@globalent.com','+1-555-0103','BRN-345678','TAX-901234','ACTIVE',null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'));
REM INSERTING into PROPERTYPRO.TENANT_INVOICES
SET DEFINE OFF;
Insert into PROPERTYPRO.TENANT_INVOICES (INVOICE_ID,INVOICE_NUMBER,TENANT_ID,LEASE_ID,PROPERTY_ID,INVOICE_TYPE,INVOICE_DATE,DUE_DATE,BILLING_PERIOD_START,BILLING_PERIOD_END,AMOUNT,VAT_RATE,VAT_AMOUNT,WITHHOLDING_TAX_RATE,WITHHOLDING_TAX_AMOUNT,TOTAL_AMOUNT,NET_AMOUNT_DUE,AMOUNT_PAID,BALANCE,PAYMENT_METHOD,PAYMENT_REFERENCE,STATUS,PAYMENT_DATE,DAYS_OVERDUE,COLLECTION_STATUS,GL_ACCOUNT_CODE,ERP_INVOICE_NUMBER,ERP_SYNC_STATUS,ERP_SYNC_DATE,ERP_ERROR_MESSAGE,DESCRIPTION,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (1,'INV-202602-211185',3,null,21,'RENT',to_date('22-FEB-26','DD-MON-RR'),to_date('22-MAR-26','DD-MON-RR'),null,null,25000,16,4000,10,2500,29000,26500,0,null,null,null,'PENDING',null,null,null,null,null,null,null,null,null,null,to_date('22-FEB-26','DD-MON-RR'),null,to_date('22-FEB-26','DD-MON-RR'));
REM INSERTING into PROPERTYPRO.USERS
SET DEFINE OFF;
Insert into PROPERTYPRO.USERS (USER_ID,USERNAME,EMAIL,PASSWORD_HASH,FULL_NAME,ROLE,STATUS,CREATED_DATE,LAST_LOGIN_DATE) values (1,'admin','admin@propertypro.com','$2b$10$X59oXpS6976Jq6S4XCGtTOSUSJJSLUy.lFZJviqUvqq7cno4dOaui','Administrator','ADMIN','ACTIVE',to_date('17-FEB-26','DD-MON-RR'),null);
REM INSERTING into PROPERTYPRO.VENDORS
SET DEFINE OFF;
Insert into PROPERTYPRO.VENDORS (VENDOR_ID,VENDOR_CODE,VENDOR_NAME,VENDOR_TYPE,CONTACT_PERSON,CONTACT_EMAIL,CONTACT_PHONE,ADDRESS,BUSINESS_REGISTRATION_NUMBER,TAX_ID,STATUS,RATING,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (21,'VND-1771785281238','Acme Maintenance Ltd','SERVICE','John Kamau','john@acme.co.ke','+254712345678','Nairobi, Industrial Area',null,null,'ACTIVE',null,null,to_date('22-FEB-26','DD-MON-RR'),null,to_date('22-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.VENDORS (VENDOR_ID,VENDOR_CODE,VENDOR_NAME,VENDOR_TYPE,CONTACT_PERSON,CONTACT_EMAIL,CONTACT_PHONE,ADDRESS,BUSINESS_REGISTRATION_NUMBER,TAX_ID,STATUS,RATING,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (1,'VEN-001','ABC Maintenance Services','MAINTENANCE','Mike Wilson','mike@abcmaint.com','+1-555-0201','100 Service Lane, New York, NY 10002',null,null,'ACTIVE',4.5,null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'));
Insert into PROPERTYPRO.VENDORS (VENDOR_ID,VENDOR_CODE,VENDOR_NAME,VENDOR_TYPE,CONTACT_PERSON,CONTACT_EMAIL,CONTACT_PHONE,ADDRESS,BUSINESS_REGISTRATION_NUMBER,TAX_ID,STATUS,RATING,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (2,'VEN-002','XYZ HVAC Solutions','HVAC','Sarah Brown','sarah@xyzhvac.com','+1-555-0202','200 Tech Street, Chicago, IL 60602',null,null,'ACTIVE',4.8,null,to_date('17-FEB-26','DD-MON-RR'),null,to_date('17-FEB-26','DD-MON-RR'));
REM INSERTING into PROPERTYPRO.WORK_ORDERS
SET DEFINE OFF;
Insert into PROPERTYPRO.WORK_ORDERS (WORK_ORDER_ID,WORK_ORDER_NUMBER,PROPERTY_ID,ASSET_ID,TITLE,WORK_ORDER_TYPE,PRIORITY,ASSIGNED_TO,VENDOR_ID,REPORTED_DATE,SCHEDULED_DATE,COMPLETED_DATE,STATUS,ESTIMATED_COST,ACTUAL_COST,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (3,'WO-1771783325735',2,null,'HVAC repair – Floor 3','CORRECTIVE','MEDIUM',null,2,to_date('22-FEB-26','DD-MON-RR'),to_date('22-FEB-26','DD-MON-RR'),null,'OPEN',null,null,null,to_date('22-FEB-26','DD-MON-RR'),null,to_date('22-FEB-26','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index IDX_WO_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_WO_STATUS" ON "PROPERTYPRO"."WORK_ORDERS" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_REQUESTS_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_REQUESTS_STATUS" ON "PROPERTYPRO"."LEASE_REQUESTS" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_INVOICE_TENANT
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_INVOICE_TENANT" ON "PROPERTYPRO"."TENANT_INVOICES" ("TENANT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_PROPERTY_CITY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_PROPERTY_CITY" ON "PROPERTYPRO"."PROPERTIES" ("CITY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_COMPLIANCE_CATEGORY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_COMPLIANCE_CATEGORY" ON "PROPERTYPRO"."COMPLIANCE_RECORDS" ("COMPLIANCE_CATEGORY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_COMPLIANCE_DUE_DATE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_COMPLIANCE_DUE_DATE" ON "PROPERTYPRO"."COMPLIANCE_RECORDS" ("DUE_DATE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_END_DATE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_END_DATE" ON "PROPERTYPRO"."LEASES" ("LEASE_END_DATE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_INVOICE_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_INVOICE_STATUS" ON "PROPERTYPRO"."TENANT_INVOICES" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_TENANT_TYPE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_TENANT_TYPE" ON "PROPERTYPRO"."TENANTS" ("TENANT_TYPE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_INVOICE_PROPERTY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_INVOICE_PROPERTY" ON "PROPERTYPRO"."TENANT_INVOICES" ("PROPERTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_PROPERTY_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_PROPERTY_STATUS" ON "PROPERTYPRO"."PROPERTIES" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_COMPLIANCE_PROPERTY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_COMPLIANCE_PROPERTY" ON "PROPERTYPRO"."COMPLIANCE_RECORDS" ("PROPERTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_TENANT
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_TENANT" ON "PROPERTYPRO"."LEASES" ("TENANT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_INVOICE_DUE_DATE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_INVOICE_DUE_DATE" ON "PROPERTYPRO"."TENANT_INVOICES" ("DUE_DATE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_REQUESTS_CREATED
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_REQUESTS_CREATED" ON "PROPERTYPRO"."LEASE_REQUESTS" ("CREATED_DATE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_INVOICE_COLLECTION
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_INVOICE_COLLECTION" ON "PROPERTYPRO"."TENANT_INVOICES" ("COLLECTION_STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_NEXT_ESCALATION
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_NEXT_ESCALATION" ON "PROPERTYPRO"."LEASES" ("NEXT_ESCALATION_DATE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_COMPLIANCE_RISK
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_COMPLIANCE_RISK" ON "PROPERTYPRO"."COMPLIANCE_RECORDS" ("RISK_LEVEL") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_WO_PRIORITY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_WO_PRIORITY" ON "PROPERTYPRO"."WORK_ORDERS" ("PRIORITY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_REQUESTS_USER
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_REQUESTS_USER" ON "PROPERTYPRO"."LEASE_REQUESTS" ("REQUESTED_BY_USER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_WO_PROPERTY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_WO_PROPERTY" ON "PROPERTYPRO"."WORK_ORDERS" ("PROPERTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_REQUESTS_PROPERTY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_REQUESTS_PROPERTY" ON "PROPERTYPRO"."LEASE_REQUESTS" ("PROPERTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_ASSET_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_ASSET_STATUS" ON "PROPERTYPRO"."ASSETS" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_PROPERTY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_PROPERTY" ON "PROPERTYPRO"."LEASES" ("PROPERTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_PROPERTY_TYPE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_PROPERTY_TYPE" ON "PROPERTYPRO"."PROPERTIES" ("PROPERTY_TYPE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_RECEIPT_INVOICE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_RECEIPT_INVOICE" ON "PROPERTYPRO"."PAYMENT_RECEIPTS" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_SPACE_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_SPACE_STATUS" ON "PROPERTYPRO"."SPACES" ("OCCUPANCY_STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_RECEIPT_DATE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_RECEIPT_DATE" ON "PROPERTYPRO"."PAYMENT_RECEIPTS" ("PAYMENT_DATE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_COMPLIANCE_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_COMPLIANCE_STATUS" ON "PROPERTYPRO"."COMPLIANCE_RECORDS" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_RECEIPT_TENANT
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_RECEIPT_TENANT" ON "PROPERTYPRO"."PAYMENT_RECEIPTS" ("TENANT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_STATUS" ON "PROPERTYPRO"."LEASES" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_LEASE_SPACE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_LEASE_SPACE" ON "PROPERTYPRO"."LEASES" ("SPACE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_TENANT_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_TENANT_STATUS" ON "PROPERTYPRO"."TENANTS" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_INVOICE_LEASE
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_INVOICE_LEASE" ON "PROPERTYPRO"."TENANT_INVOICES" ("LEASE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_ASSET_PROPERTY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_ASSET_PROPERTY" ON "PROPERTYPRO"."ASSETS" ("PROPERTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_SPACE_PROPERTY
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_SPACE_PROPERTY" ON "PROPERTYPRO"."SPACES" ("PROPERTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_USERS_STATUS
--------------------------------------------------------

  CREATE INDEX "PROPERTYPRO"."IDX_USERS_STATUS" ON "PROPERTYPRO"."USERS" ("STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table VENDORS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."VENDORS" MODIFY ("VENDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."VENDORS" MODIFY ("VENDOR_CODE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."VENDORS" MODIFY ("VENDOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."VENDORS" ADD CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLACKLISTED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."VENDORS" ADD PRIMARY KEY ("VENDOR_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."VENDORS" ADD UNIQUE ("VENDOR_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENT_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."RENT_SCHEDULE" MODIFY ("SCHEDULE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."RENT_SCHEDULE" MODIFY ("LEASE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."RENT_SCHEDULE" MODIFY ("DUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."RENT_SCHEDULE" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."RENT_SCHEDULE" ADD CHECK (status IN ('PENDING', 'PAID', 'OVERDUE', 'WAIVED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."RENT_SCHEDULE" ADD PRIMARY KEY ("SCHEDULE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPACES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."SPACES" MODIFY ("SPACE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."SPACES" MODIFY ("SPACE_CODE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."SPACES" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."SPACES" MODIFY ("SPACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."SPACES" ADD CHECK (space_type IN ('OFFICE', 'RETAIL', 'WAREHOUSE', 'PARKING', 'COMMON_AREA')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."SPACES" ADD CHECK (occupancy_status IN ('VACANT', 'OCCUPIED', 'RESERVED', 'MAINTENANCE')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."SPACES" ADD PRIMARY KEY ("SPACE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."SPACES" ADD UNIQUE ("SPACE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPERTIES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."PROPERTIES" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" MODIFY ("PROPERTY_CODE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" MODIFY ("PROPERTY_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" ADD CHECK (property_type IN ('COMMERCIAL', 'RESIDENTIAL', 'INDUSTRIAL', 'MIXED_USE')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" ADD CHECK (status IN ('ACTIVE', 'INACTIVE', 'UNDER_CONSTRUCTION', 'SOLD')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" ADD PRIMARY KEY ("PROPERTY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" ADD UNIQUE ("PROPERTY_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."PROPERTIES" MODIFY ("ADDRESS_LINE1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TENANT_INVOICES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" MODIFY ("INVOICE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" MODIFY ("TENANT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" MODIFY ("DUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" MODIFY ("TOTAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD CHECK (invoice_type IN ('RENT', 'CAM', 'UTILITIES', 'PARKING', 'LATE_FEE', 'OTHER')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD CHECK (payment_method IN ('BANK_TRANSFER', 'M_PESA', 'CHEQUE', 'CASH', 'CARD')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD CHECK (status IN ('DRAFT', 'PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD CHECK (collection_status IN ('CURRENT', '1_30_DAYS', '31_60_DAYS', '61_90_DAYS', '90_PLUS_DAYS')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD CHECK (erp_sync_status IN ('PENDING', 'SYNCED', 'FAILED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD PRIMARY KEY ("INVOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD UNIQUE ("INVOICE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."USERS" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."USERS" ADD CHECK (role IN ('ADMIN', 'MANAGER', 'USER')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."USERS" ADD CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT_RECEIPTS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" MODIFY ("RECEIPT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" MODIFY ("RECEIPT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" MODIFY ("TENANT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" MODIFY ("AMOUNT_PAID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" ADD CHECK (payment_method IN ('BANK_TRANSFER', 'M_PESA', 'CHEQUE', 'CASH', 'CARD')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" ADD CHECK (erp_sync_status IN ('PENDING', 'SYNCED', 'FAILED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" ADD PRIMARY KEY ("RECEIPT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" ADD UNIQUE ("RECEIPT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPLIANCE_RECORDS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" MODIFY ("COMPLIANCE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" MODIFY ("COMPLIANCE_CODE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" MODIFY ("COMPLIANCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" MODIFY ("COMPLIANCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" ADD CHECK (compliance_category IN ('NEMA', 'COUNTY', 'FIRE', 'DOSH', 'WATER', 'ENERGY', 'KRA', 'HEALTH', 'INSURANCE', 'SECURITY')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" ADD CHECK (frequency IN ('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'BIENNIAL')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" ADD CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" ADD CHECK (risk_level IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" ADD PRIMARY KEY ("COMPLIANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" ADD UNIQUE ("COMPLIANCE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CREDIT_NOTES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" MODIFY ("CREDIT_NOTE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" MODIFY ("CREDIT_NOTE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" MODIFY ("TENANT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" ADD CHECK (status IN ('PENDING', 'APPROVED', 'APPLIED', 'CANCELLED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" ADD CHECK (erp_sync_status IN ('PENDING', 'SYNCED', 'FAILED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" ADD PRIMARY KEY ("CREDIT_NOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" ADD UNIQUE ("CREDIT_NOTE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LEASES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."LEASES" MODIFY ("LEASE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASES" MODIFY ("LEASE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASES" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASES" MODIFY ("TENANT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASES" MODIFY ("LEASE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASES" MODIFY ("LEASE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASES" MODIFY ("BASE_RENT" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASES" MODIFY ("RENT_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CHECK (security_deposit_type IN ('CASH', 'BANK_GUARANTEE', 'INSURANCE_BOND')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CHECK (payment_frequency IN ('MONTHLY', 'QUARTERLY', 'ANNUALLY')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CHECK (lease_type IN ('COMMERCIAL', 'RESIDENTIAL', 'INDUSTRIAL', 'RETAIL', 'OFFICE')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CHECK (lease_category IN ('GROSS', 'NET', 'TRIPLE_NET', 'MODIFIED_GROSS')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CHECK (status IN ('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED', 'RENEWED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CHECK (escalation_type IN ('FIXED', 'CPI_BASED', 'MARKET_BASED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CHECK (escalation_frequency IN ('ANNUAL', 'BIENNIAL', 'QUARTERLY')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD PRIMARY KEY ("LEASE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD UNIQUE ("LEASE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORK_ORDERS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" MODIFY ("WORK_ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" MODIFY ("WORK_ORDER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" ADD CHECK (work_order_type IN ('CORRECTIVE', 'PREVENTIVE', 'INSPECTION', 'PROJECT')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" ADD CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" ADD CHECK (status IN ('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" ADD PRIMARY KEY ("WORK_ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" ADD UNIQUE ("WORK_ORDER_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSETS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."ASSETS" MODIFY ("ASSET_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."ASSETS" MODIFY ("ASSET_CODE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."ASSETS" MODIFY ("ASSET_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."ASSETS" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."ASSETS" ADD CHECK (status IN ('ACTIVE', 'INACTIVE', 'UNDER_MAINTENANCE', 'RETIRED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."ASSETS" ADD PRIMARY KEY ("ASSET_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."ASSETS" ADD UNIQUE ("ASSET_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LEASE_REQUESTS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."LEASE_REQUESTS" MODIFY ("REQUEST_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASE_REQUESTS" MODIFY ("REQUESTED_BY_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASE_REQUESTS" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."LEASE_REQUESTS" ADD PRIMARY KEY ("LEASE_REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASE_REQUESTS" MODIFY ("LEASE_REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TENANTS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."TENANTS" MODIFY ("TENANT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANTS" MODIFY ("TENANT_CODE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANTS" MODIFY ("TENANT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROPERTYPRO"."TENANTS" ADD CHECK (tenant_type IN ('INDIVIDUAL', 'CORPORATE', 'GOVERNMENT')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANTS" ADD CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLACKLISTED')) ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANTS" ADD PRIMARY KEY ("TENANT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANTS" ADD UNIQUE ("TENANT_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSETS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."ASSETS" ADD CONSTRAINT "FK_ASSET_PROPERTY" FOREIGN KEY ("PROPERTY_ID")
	  REFERENCES "PROPERTYPRO"."PROPERTIES" ("PROPERTY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPLIANCE_RECORDS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."COMPLIANCE_RECORDS" ADD CONSTRAINT "FK_COMPLIANCE_PROPERTY" FOREIGN KEY ("PROPERTY_ID")
	  REFERENCES "PROPERTYPRO"."PROPERTIES" ("PROPERTY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CREDIT_NOTES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" ADD CONSTRAINT "FK_CN_INVOICE" FOREIGN KEY ("INVOICE_ID")
	  REFERENCES "PROPERTYPRO"."TENANT_INVOICES" ("INVOICE_ID") ENABLE;
  ALTER TABLE "PROPERTYPRO"."CREDIT_NOTES" ADD CONSTRAINT "FK_CN_TENANT" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "PROPERTYPRO"."TENANTS" ("TENANT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEASES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CONSTRAINT "FK_LEASE_PROPERTY" FOREIGN KEY ("PROPERTY_ID")
	  REFERENCES "PROPERTYPRO"."PROPERTIES" ("PROPERTY_ID") ENABLE;
  ALTER TABLE "PROPERTYPRO"."LEASES" ADD CONSTRAINT "FK_LEASE_TENANT" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "PROPERTYPRO"."TENANTS" ("TENANT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT_RECEIPTS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" ADD CONSTRAINT "FK_RECEIPT_INVOICE" FOREIGN KEY ("INVOICE_ID")
	  REFERENCES "PROPERTYPRO"."TENANT_INVOICES" ("INVOICE_ID") ENABLE;
  ALTER TABLE "PROPERTYPRO"."PAYMENT_RECEIPTS" ADD CONSTRAINT "FK_RECEIPT_TENANT" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "PROPERTYPRO"."TENANTS" ("TENANT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENT_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."RENT_SCHEDULE" ADD CONSTRAINT "FK_RENT_LEASE" FOREIGN KEY ("LEASE_ID")
	  REFERENCES "PROPERTYPRO"."LEASES" ("LEASE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPACES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."SPACES" ADD CONSTRAINT "FK_SPACE_PROPERTY" FOREIGN KEY ("PROPERTY_ID")
	  REFERENCES "PROPERTYPRO"."PROPERTIES" ("PROPERTY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TENANT_INVOICES
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD CONSTRAINT "FK_INVOICE_TENANT" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "PROPERTYPRO"."TENANTS" ("TENANT_ID") ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD CONSTRAINT "FK_INVOICE_LEASE" FOREIGN KEY ("LEASE_ID")
	  REFERENCES "PROPERTYPRO"."LEASES" ("LEASE_ID") ENABLE;
  ALTER TABLE "PROPERTYPRO"."TENANT_INVOICES" ADD CONSTRAINT "FK_INVOICE_PROPERTY" FOREIGN KEY ("PROPERTY_ID")
	  REFERENCES "PROPERTYPRO"."PROPERTIES" ("PROPERTY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORK_ORDERS
--------------------------------------------------------

  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" ADD CONSTRAINT "FK_WO_PROPERTY" FOREIGN KEY ("PROPERTY_ID")
	  REFERENCES "PROPERTYPRO"."PROPERTIES" ("PROPERTY_ID") ENABLE;
  ALTER TABLE "PROPERTYPRO"."WORK_ORDERS" ADD CONSTRAINT "FK_WO_ASSET" FOREIGN KEY ("ASSET_ID")
	  REFERENCES "PROPERTYPRO"."ASSETS" ("ASSET_ID") ENABLE;
